services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    depends_on:
      - postgres
      - mongodb
    ports:
      - "80:80"

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8080:8080"

volumes:
  pgdata:
    driver: local
  mongodata:
    driver: local

networks:
  default:
    driver: bridge
